Repository Ankit-Saha08/AIFF_Live_Updates, pull requests merged in 2023-10, with the labels that each got.

#3 fix: mobile view
  IndianFootball.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#5 fixing mobile view
  IndianFootball.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#9 Fixed the alignments of the content and updated the ui
  IndianFootball.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#16 Add a basic Navbar #13
  IndianFootball.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#20 Adding Contact Us Page #10
  IndianFootball.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#26 proper alignment of text inside card
  IndianFootball.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#27 Updated the IWL link
  index.html
Labels: hacktoberfest-accepted

#38 Added footer
  .gitignore
  IndianFootball.css
  icons/facebook.png
  icons/instagram.png
  icons/twitter.png
  icons/youtube.png
  index.html
Labels: hacktoberfest

#35 Update Contact_Us.html
  Contact_Us.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#40 Added a Bootstrap Footer
  IndianFootball.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 Updated kits section
  IndianFootball.css
  index.html
  third.png
Labels: hacktoberfest, hacktoberfest-accepted
